# Generated by Django 4.0.1 on 2022-01-13 17:16

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='resume',
            field=django_bleach.models.BleachField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='under_service_area',
            field=django_bleach.models.BleachField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=django_bleach.models.BleachField(blank=True),
        ),
    ]
