# Generated by Django 3.2.10 on 2022-01-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_contractor_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='under_service_area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
