# Generated by Django 3.2.11 on 2022-01-23 14:03

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('device_cntrl', '0004_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='details',
            field=django_bleach.models.BleachField(blank=True, null=True),
        ),
    ]
