# Generated by Django 3.2.11 on 2022-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_cntrl', '0005_alter_device_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='firmware',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y-%m-%d/'),
        ),
    ]
