# Generated by Django 3.2.11 on 2022-02-22 14:34

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('device_cntrl', '0006_device_firmware'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='face_detection',
            field=django_bleach.models.BleachField(blank=True, null=True),
        ),
    ]
