# Generated by Django 3.2.11 on 2022-02-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_cntrl', '0007_device_face_detection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='face_detection',
        ),
    ]
