# Generated by Django 3.2.11 on 2022-01-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveupdatenotification',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
