# Generated by Django 3.2.11 on 2022-01-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_saveupdatenotification_is_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveupdatenotification',
            name='version',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
