# Generated by Django 3.2.7 on 2021-12-05 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device_cntrl', '0001_initial'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('devices', models.ManyToManyField(blank=True, null=True, related_name='used_home', to='device_cntrl.Device')),
                ('main_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contractor')),
                ('members', models.ManyToManyField(related_name='house_member', to='accounts.Customer')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='own_house', to='accounts.customer')),
            ],
        ),
    ]
