# Generated by Django 3.2.7 on 2021-12-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_cntrl', '0001_initial'),
        ('home_cntrl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='devices',
            field=models.ManyToManyField(related_name='used_home', to='device_cntrl.Device'),
        ),
    ]
