# Generated by Django 3.2.7 on 2021-12-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_cntrl', '0002_alter_house_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='devices',
        ),
    ]
