# Generated by Django 4.0.1 on 2022-01-24 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpdates',
            new_name='FileUpdate',
        ),
    ]
