# Generated by Django 3.2.11 on 2022-02-03 18:24

from django.db import migrations, models
import django.db.models.deletion
import django_bleach.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('details', django_bleach.models.BleachField(blank=True, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_on_time', models.TimeField(blank=True, null=True)),
                ('turn_off_time', models.TimeField(blank=True, null=True)),
                ('volume', models.CharField(default='NOT SET', max_length=8)),
                ('state', models.CharField(default='NOT SET', max_length=8)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.device')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_volume', models.CharField(default='NOT SET', max_length=8)),
                ('new_volume', models.CharField(default='NOT SET', max_length=8)),
                ('old_state', models.CharField(default='NOT SET', max_length=8)),
                ('new_state', models.CharField(default='NOT SET', max_length=8)),
                ('time', models.TimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recommender.deviceinused')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('main_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contractor')),
                ('members', models.ManyToManyField(related_name='house_member', to='accounts.Customer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_house', to='accounts.customer')),
            ],
        ),
        migrations.AddField(
            model_name='deviceinused',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.house'),
        ),
    ]
